version: "2"
services:
  master:
    image: docker.jenkins.master:1.0
    ports:
    - "8080:8080"
    - "50000:50000"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - jenkins-master:/var/jenkins_home

#  worker:
#
#      image: docker.jenkins.slave:1.0
#       command: -master http://172.18.0.4:8080 -username jenkins -password jenkins
#       volumes:
#       - jenkins-worker:/var/jenkins_home/worker

  nexus:
    image: docker.nexus:1.0
    ports:
    - "8081:8081"
    volumes:
    - nexus-master:/var/nexus


volumes:
  jenkins-master:
#  jenkins-worker:
  nexus-master:
